// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAtLeTKXkL2nsGrFC0rIzHKqU2_D27rCY',
    appId: '1:113920208519:web:982a715502323423f11222',
    messagingSenderId: '113920208519',
    projectId: 'fyp1-f09f5',
    authDomain: 'fyp1-f09f5.firebaseapp.com',
    storageBucket: 'fyp1-f09f5.firebasestorage.app',
    measurementId: 'G-H9ZJLC2TQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCymnsL7SzhT2kEl9NF5FaelXqYGFRg5QY',
    appId: '1:113920208519:android:25f3e76856fca4bef11222',
    messagingSenderId: '113920208519',
    projectId: 'fyp1-f09f5',
    storageBucket: 'fyp1-f09f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5Mva1ioJDF2fCVeuNVW7Y28BHu29PAI',
    appId: '1:113920208519:ios:6a2ace268c2f6386f11222',
    messagingSenderId: '113920208519',
    projectId: 'fyp1-f09f5',
    storageBucket: 'fyp1-f09f5.firebasestorage.app',
    iosBundleId: 'com.example.fypTry2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU5Mva1ioJDF2fCVeuNVW7Y28BHu29PAI',
    appId: '1:113920208519:ios:6a2ace268c2f6386f11222',
    messagingSenderId: '113920208519',
    projectId: 'fyp1-f09f5',
    storageBucket: 'fyp1-f09f5.firebasestorage.app',
    iosBundleId: 'com.example.fypTry2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAtLeTKXkL2nsGrFC0rIzHKqU2_D27rCY',
    appId: '1:113920208519:web:06677c23ec197996f11222',
    messagingSenderId: '113920208519',
    projectId: 'fyp1-f09f5',
    authDomain: 'fyp1-f09f5.firebaseapp.com',
    storageBucket: 'fyp1-f09f5.firebasestorage.app',
    measurementId: 'G-2DVB1QBSGT',
  );
}
